### ISSUE TITLE
Question: how to create/edit AMRs

### ISSUE THREAD

**Issue by francisjervis** [tokenmill/accelerated-text#121]
Hi, I cannot find the answer to this in the docs - for instance I want to create "is-owned-by." Not sure if this just undocumented or a new feature request?

EDIT: looking into the code this is of course defined in the the concept-net YML files, so I guess this is a feature request for editing those in the front end!

**Comment by zaibacu** [comment]
Hello,

Yes, at the moment there's no proper way to do it via UI. Technically, we do have graphQL API to add/update AMRs and it would be matter of creating UI part for that, but there are two pieces to this puzzle: 
- Those yaml files, which are basically mapping, it tells what arguments there will be, what types these will have and what functions `oper` will they use.
- `oper` parts, which are actual functions implemented in GrammaticalFramework. 

So the mapping part can done (and hopefully will be done in near future), but as those functions goes - most likely we will just cover all of common scenarios and will add new ones on request

**Comment by francisjervis** [comment]
It looks from #128 like there is an AMR editor in the works? Excited to try it!
