### ISSUE TITLE
Add part of speech tag to dictionary items

### ISSUE THREAD

**Issue by francisjervis** [tokenmill/accelerated-text#122]
Some supplied dictionary items are marked as verbs (VV) etc. It does not seem to be possible to add these tags to newly created items.

**Comment by zmedelis** [comment]
We are now working on providing full support for managing multi-language dictionaries. Part of speech tags will be available. Though at the level of constructing document plans I'd love to figure out the way which does not require a user to know anything about the grammar, even if a word is a verb.

**Comment by zmedelis** [comment]
I have added a document describing how dictionary items are to be [managed](https://github.com/tokenmill/accelerated-text/wiki/Dictionary-management).

There is another [bug](https://github.com/tokenmill/accelerated-text/issues/148) which prevents from managing the dictionary via UI, but following instructions in the wiki doc dictionaries items can be fully described.
