### ISSUE TITLE
Crash when adding new item to dictionary

### ISSUE THREAD

**Issue by francisjervis** [tokenmill/accelerated-text#148]
Steps to reproduce:
Enter string in entry field and click "add" in Dictionary pane.
Logs:

` 2020-03-28 07:09:16,015 DEBUG a.n.g.service - ** Incomplete concrete **
acc-text-api_1         | incomplete concrete DefaultBody of Default = open Syntax, DefaultLex, ParadigmsEng in {
acc-text-api_1         |     lincat
acc-text-api_1         |         Segment02, DocumentPlan01 = Str ;
acc-text-api_1         |     lin
acc-text-api_1         |         Function01 Segment02 = Segment02 ;
acc-text-api_1         |         Function02 = "" ;
acc-text-api_1         | }
acc-text-api_1         | 
acc-text-api_1         | 2020-03-28 07:09:16,016 DEBUG a.n.g.service - ** Concrete **
acc-text-api_1         | concrete DefaultInstance of Default = DefaultBody with 
acc-text-api_1         |   (Syntax=SyntaxEng),
acc-text-api_1         |   (DefaultLex = DefaultLexEng);
acc-text-api_1         | 2020-03-28 07:09:16,017 DEBUG a.n.g.service - ** Lex interface **
acc-text-api_1         | interface DefaultLex = {
acc-text-api_1         | }
acc-text-api_1         | 
acc-text-api_1         | 2020-03-28 07:09:16,017 DEBUG a.n.g.service - ** Lex data **
acc-text-api_1         | resource DefaultLexEng = open SyntaxEng, ParadigmsEng, MorphoEng in {
acc-text-api_1         | }
acc-text-api_1         | 
acc-text-api_1         | 2020-03-28 07:09:20,431 ERROR a.error - Uri: /_graphql Stacktrace: 
acc-text-api_1         | java.lang.NullPointerException: null
acc-text-api_1         |  at clojure.core$name.invokeStatic (core.clj:1595)
acc-text-api_1         |     clojure.core$name.invoke (core.clj:1589)
acc-text-api_1         |     api.graphql.translate.dictionary$schema__GT_default_multilang_dict_item.invokeStatic (dictionary.clj:89)
acc-text-api_1         |     api.graphql.translate.dictionary$schema__GT_default_multilang_dict_item.invoke (dictionary.clj:84)
acc-text-api_1         |     api.graphql.domain.dictionary$create_dictionary_item.invokeStatic (dictionary.clj:28)
acc-text-api_1         |     api.graphql.domain.dictionary$create_dictionary_item.invoke (dictionary.clj:27)
acc-text-api_1         |     clojure.lang.Var.invoke (Var.java:393)
acc-text-api_1         |     com.walmartlabs.lacinia.schema$wrap_resolver_to_ensure_resolver_result$fn__12518.invoke (schema.clj:612)
acc-text-api_1         |     com.walmartlabs.lacinia.executor$invoke_resolver_for_field.invokeStatic (executor.clj:137)
acc-text-api_1         |     com.walmartlabs.lacinia.executor$invoke_resolver_for_field.invoke (executor.clj:115)
acc-text-api_1         |     com.walmartlabs.lacinia.executor$resolve_and_select.invokeStatic (executor.clj:451)
acc-text-api_1         |     com.walmartlabs.lacinia.executor$resolve_and_select.invoke (executor.clj:344)
acc-text-api_1         |     com.walmartlabs.lacinia.executor$eval14396$fn__14397.invoke (executor.clj:230)
acc-text-api_1         |     clojure.lang.MultiFn.invoke (MultiFn.java:234)
acc-text-api_1         |     com.walmartlabs.lacinia.executor$combine_selection_results_sync$fn__14424.invoke (executor.clj:322)
acc-text-api_1         |     com.walmartlabs.lacinia.resolve.ResolverResultImpl.on_deliver_BANG_ (resolve.clj:109)
acc-text-api_1         |     com.walmartlabs.lacinia.executor$combine_selection_results_sync.invokeStatic (executor.clj:318)
acc-text-api_1         |     com.walmartlabs.lacinia.executor$combine_selection_results_sync.invoke (executor.clj:313)
acc-text-api_1         |     com.walmartlabs.lacinia.executor$execute_nested_selections_sync$fn__14431.invoke (executor.clj:340)
acc-text-api_1         |     clojure.lang.ArrayChunk.reduce (ArrayChunk.java:58)
acc-text-api_1         |     clojure.core.protocols$fn__8154.invokeStatic (protocols.clj:136)
acc-text-api_1         |     clojure.core.protocols/fn (protocols.clj:124)
acc-text-api_1         |     clojure.core.protocols$fn__8114$G__8109__8123.invoke (protocols.clj:19)
acc-text-api_1         |     clojure.core.protocols$seq_reduce.invokeStatic (protocols.clj:31)
acc-text-api_1         |     clojure.core.protocols$fn__8146.invokeStatic (protocols.clj:75)
acc-text-api_1         |     clojure.core.protocols/fn (protocols.clj:75)
acc-text-api_1         |     clojure.core.protocols$fn__8088$G__8083__8101.invoke (protocols.clj:13)
acc-text-api_1         |     clojure.core$reduce.invokeStatic (core.clj:6828)
acc-text-api_1         |     clojure.core$reduce.invoke (core.clj:6810)
acc-text-api_1         |     com.walmartlabs.lacinia.executor$execute_nested_selections_sync.invokeStatic (executor.clj:340)
acc-text-api_1         |     com.walmartlabs.lacinia.executor$execute_nested_selections_sync.invoke (executor.clj:331)
acc-text-api_1         |     com.walmartlabs.lacinia.executor$execute_query.invokeStatic (executor.clj:489)
acc-text-api_1         |     com.walmartlabs.lacinia.executor$execute_query.invoke (executor.clj:458)
acc-text-api_1         |     com.walmartlabs.lacinia$execute_parsed_query_async.invokeStatic (lacinia.clj:54)
acc-text-api_1         |     com.walmartlabs.lacinia$execute_parsed_query_async.invoke (lacinia.clj:29)
acc-text-api_1         |     com.walmartlabs.lacinia$execute_parsed_query.invokeStatic (lacinia.clj:63)
acc-text-api_1         |     com.walmartlabs.lacinia$execute_parsed_query.invoke (lacinia.clj:56)
acc-text-api_1         |     com.walmartlabs.lacinia$execute.invokeStatic (lacinia.clj:121)
acc-text-api_1         |     com.walmartlabs.lacinia$execute.invoke (lacinia.clj:70)
acc-text-api_1         |     api.graphql.core$handle.invokeStatic (core.clj:68)
acc-text-api_1         |     api.graphql.core$handle.invoke (core.clj:66)
acc-text-api_1         |     api.server$fn__28937.invokeStatic (server.clj:53)
acc-text-api_1         |     api.server/fn (server.clj:50)
acc-text-api_1         |     reitit.ring.middleware.exception$wrap$fn__19795$fn__19796.invoke (exception.clj:49)
acc-text-api_1         |     muuntaja.middleware$wrap_format_response$fn__26502.invoke (middleware.clj:132)
acc-text-api_1         |     api.server$wrap_response$fn__28933.invoke (server.clj:45)
acc-text-api_1         |     ring.middleware.params$wrap_params$fn__26449.invoke (params.clj:67)
acc-text-api_1         |     muuntaja.middleware$wrap_format_negotiate$fn__26495.invoke (middleware.clj:96)
acc-text-api_1         |     reitit.ring$ring_handler$fn__19761.invoke (ring.cljc:292)
acc-text-api_1         |     clojure.lang.AFn.applyToHelper (AFn.java:154)
acc-text-api_1         |     clojure.lang.AFn.applyTo (AFn.java:144)
acc-text-api_1         |     clojure.lang.AFunction$1.doInvoke (AFunction.java:31)
acc-text-api_1         |     clojure.lang.RestFn.invoke (RestFn.java:408)
acc-text-api_1         |     clojure.lang.Var.invoke (Var.java:384)
acc-text-api_1         |     org.httpkit.server.HttpHandler.run (RingHandler.java:115)
acc-text-api_1         |     java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
acc-text-api_1         |     java.util.concurrent.FutureTask.run (FutureTask.java:266)
acc-text-api_1         |     java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
acc-text-api_1         |     java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
acc-text-api_1         |     java.lang.Thread.run (Thread.java:748)
acc-text-api_1         | 
`

**Comment by zaibacu** [comment]
This is due to current refactoring (still in progress). More sophisticated structure is used and UI is not updated accordingly. Some hacks were made to make it at least partially work, but it seems there are still problems :) 

Better way would be editing https://github.com/tokenmill/accelerated-text/blob/master/api/resources/dictionary/eng.edn directly

Few examples:
```
 #:acc-text.nlg.dictionary.item{:key      "property_1_N"
                                :sense    "1"
                                :category "N"
                                :language "Eng"
                                :forms    ["property" "properties"]}
```
For nouns category is `N`, and forms array is basically singular and plural form.

Verb:
```
 #:acc-text.nlg.dictionary.item{:key      "see_1_V"
                                :sense    "1"
                                :category "V"
                                :language "Eng"
                                :forms    ["see" "saw" "seen"]}
```
Forms array can be single word if it's totally regular verb. If it is common irregular verb - three forms can be providen (like in this example). And if it is totally irregular - five forms.

Somehow we will need to figure out a way to fit all of this metadata in UI

**Comment by zmedelis** [comment]
New v0.8.0 release partially this. Though for full UI based dictionary editing we'd still need to improve the UI.
