### ISSUE TITLE
can not access to swagger API

### ISSUE THREAD

**Issue by geopamplona** [tokenmill/accelerated-text#218]
Hi, I am new in Accelerated-Text !

I try download and run software, but I have problems.

First I clone repo, and run "make run-app". Then conteiners are created and run correctly. I can open web UI correctly, and create documents, etc. in http://192.168.1.131:8080/

Iam using 

Hostname | desktop
-- | --
OS Information | linux x86_64                 Ubuntu 18.04.4 LTS
Kernel Version | 4.15.0-112-generic
Total CPU | 4
Total memory | 11.7 GB

Version | 19.03.7 (API: 1.40)
-- | --
Root directory | /var/lib/docker
Storage Driver | overlay2
Logging Driver | json-file
Volume Plugins | local
Network Plugins | bridge, host, ipvlan, macvlan, null, overlay

But when I try see API in http://localhost:3001/index.html then I get error:
![imagen](https://user-images.githubusercontent.com/25028240/90310532-7a16fc00-def2-11ea-8d63-75129742deb6.png)

![imagen](https://user-images.githubusercontent.com/25028240/90310555-ceba7700-def2-11ea-82fb-17de471352b0.png)

> `acc-text-api_1        | 2020-08-15 10:22:08,001 ERROR a.error - Uri: /swagger.json Stacktrace:
> acc-text-api_1        | java.lang.Exception: Unable to resolve spec: :api.nlg.service.request/documentPlanName
> acc-text-api_1        |  at clojure.spec.alpha$reg_resolve_BANG_.invokeStatic (alpha.clj:69)
> acc-text-api_1        |     clojure.spec.alpha$reg_resolve_BANG_.invoke (alpha.clj:64)
> acc-text-api_1        |     clojure.spec.alpha$fn__1803.invokeStatic (alpha.clj:132)
> acc-text-api_1        |     clojure.spec.alpha/fn (alpha.clj:130)
> acc-text-api_1        |     clojure.spec.alpha$fn__1782$G__1777__1791.invoke (alpha.clj:121)
> acc-text-api_1        |     clojure.spec.alpha$specize.invokeStatic (alpha.clj:152)
> acc-text-api_1        |     clojure.spec.alpha$specize.invoke (alpha.clj:151)
> acc-text-api_1        |     clojure.spec.alpha$form.invokeStatic (alpha.clj:177)
> acc-text-api_1        |     clojure.spec.alpha$form.invoke (alpha.clj:173)
> acc-text-api_1        |     spec_tools.visitor$spec_dispatch.invokeStatic (visitor.cljc:13)
> acc-text-api_1        |     spec_tools.visitor$spec_dispatch.invoke (visitor.cljc:9)
> acc-text-api_1        |     clojure.lang.MultiFn.invoke (MultiFn.java:238)
> acc-text-api_1        |     spec_tools.visitor$visit.invokeStatic (visitor.cljc:52)
> acc-text-api_1        |     spec_tools.visitor$visit.invoke (visitor.cljc:26)
> acc-text-api_1        |     spec_tools.visitor$eval22199$fn__22200$fn__22201.invoke (visitor.cljc:60)
> acc-text-api_1        |     clojure.core$mapv$fn__8445.invoke (core.clj:6912)
> acc-text-api_1        |     clojure.core.protocols$fn__8159.invokeStatic (protocols.clj:168)
> acc-text-api_1        |     clojure.core.protocols/fn (protocols.clj:124)
> acc-text-api_1        |     clojure.core.protocols$fn__8114$G__8109__8123.invoke (protocols.clj:19)
> acc-text-api_1        |     clojure.core.protocols$seq_reduce.invokeStatic (protocols.clj:31)
> acc-text-api_1        |     clojure.core.protocols$fn__8146.invokeStatic (protocols.clj:75)
> acc-text-api_1        |     clojure.core.protocols/fn (protocols.clj:75)
> acc-text-api_1        |     clojure.core.protocols$fn__8088$G__8083__8101.invoke (protocols.clj:13)
> acc-text-api_1        |     clojure.core$reduce.invokeStatic (core.clj:6828)
> acc-text-api_1        |     clojure.core$mapv.invokeStatic (core.clj:6903)
> acc-text-api_1        |     clojure.core$mapv.invoke (core.clj:6903)
> acc-text-api_1        |     spec_tools.visitor$eval22199$fn__22200.invoke (visitor.cljc:60)
> acc-text-api_1        |     clojure.lang.MultiFn.invoke (MultiFn.java:239)
> acc-text-api_1        |     spec_tools.visitor$visit.invokeStatic (visitor.cljc:52)
> acc-text-api_1        |     spec_tools.visitor$visit.invoke (visitor.cljc:26)
> acc-text-api_1        |     spec_tools.visitor$eval22348$fn__22349.invoke (visitor.cljc:143)
> acc-text-api_1        |     clojure.lang.MultiFn.invoke (MultiFn.java:239)
> acc-text-api_1        |     spec_tools.visitor$visit.invokeStatic (visitor.cljc:52)
> acc-text-api_1        |     spec_tools.visitor$visit.invoke (visitor.cljc:26)
> acc-text-api_1        |     spec_tools.swagger.core$transform.invokeStatic (core.cljc:96)
> acc-text-api_1        |     spec_tools.swagger.core$transform.invoke (core.cljc:87)
> acc-text-api_1        |     spec_tools.swagger.core$eval22738$fn__22739.invoke (core.cljc:105)
> acc-text-api_1        |     clojure.lang.MultiFn.invoke (MultiFn.java:234)
> acc-text-api_1        |     spec_tools.swagger.core$eval22788$fn__22789$fn__22791.invoke (core.cljc:142)
> acc-text-api_1        |     clojure.core$map$fn__5866.invoke (core.clj:2755)
> acc-text-api_1        |     clojure.lang.LazySeq.sval (LazySeq.java:42)
> acc-text-api_1        |     clojure.lang.LazySeq.seq (LazySeq.java:51)
> acc-text-api_1        |     clojure.lang.RT.seq (RT.java:535)
> acc-text-api_1        |     clojure.core$seq__5402.invokeStatic (core.clj:137)
> acc-text-api_1        |     clojure.core$apply.invokeStatic (core.clj:660)
> acc-text-api_1        |     clojure.core$mapcat.invokeStatic (core.clj:2783)
> acc-text-api_1        |     clojure.core$mapcat.doInvoke (core.clj:2783)
> acc-text-api_1        |     clojure.lang.RestFn.invoke (RestFn.java:423)
> acc-text-api_1        |     spec_tools.swagger.core$eval22788$fn__22789.invoke (core.cljc:142)
> acc-text-api_1        |     clojure.lang.MultiFn.invoke (MultiFn.java:244)
> acc-text-api_1        |     spec_tools.swagger.core$expand_qualified_keywords$fn__22805$fn__22806.invoke (core.cljc:165)
> acc-text-api_1        |     clojure.core$fn__8429$fn__8431.invoke (core.clj:6840)
> acc-text-api_1        |     clojure.core.protocols$iter_reduce.invokeStatic (protocols.clj:49)
> acc-text-api_1        |     clojure.core.protocols$fn__8140.invokeStatic (protocols.clj:75)
> acc-text-api_1        |     clojure.core.protocols/fn (protocols.clj:75)
> acc-text-api_1        |     clojure.core.protocols$fn__8088$G__8083__8101.invoke (protocols.clj:13)
> acc-text-api_1        |     clojure.core$reduce.invokeStatic (core.clj:6828)
> acc-text-api_1        |     clojure.core$fn__8429.invokeStatic (core.clj:6830)
> acc-text-api_1        |     clojure.core/fn (core.clj:6830)
> acc-text-api_1        |     clojure.core.protocols$fn__8167$G__8162__8176.invoke (protocols.clj:175)
> acc-text-api_1        |     clojure.core$reduce_kv.invokeStatic (core.clj:6856)
> acc-text-api_1        |     clojure.core$reduce_kv.invoke (core.clj:6847)
> acc-text-api_1        |     spec_tools.swagger.core$expand_qualified_keywords$fn__22805.invoke (core.cljc:162)
> acc-text-api_1        |     clojure.walk$walk.invokeStatic (walk.clj:50)
> acc-text-api_1        |     clojure.walk$postwalk.invokeStatic (walk.clj:53)
> acc-text-api_1        |     clojure.walk$postwalk.invoke (walk.clj:53)
> acc-text-api_1        |     spec_tools.swagger.core$expand_qualified_keywords.invokeStatic (core.cljc:159)
> acc-text-api_1        |     spec_tools.swagger.core$expand_qualified_keywords.invoke (core.cljc:157)
> acc-text-api_1        |     spec_tools.swagger.core$swagger_spec.invokeStatic (core.cljc:184)
> acc-text-api_1        |     spec_tools.swagger.core$swagger_spec.invoke (core.cljc:176)
> acc-text-api_1        |     spec_tools.swagger.core$swagger_spec.invokeStatic (core.cljc:182)
> acc-text-api_1        |     spec_tools.swagger.core$swagger_spec.invoke (core.cljc:176)
> acc-text-api_1        |     reitit.coercion.spec$create$reify__22889._get_apidocs (spec.cljc:87)
> acc-text-api_1        |     reitit.coercion$get_apidocs.invokeStatic (coercion.cljc:147)
> acc-text-api_1        |     reitit.coercion$get_apidocs.invoke (coercion.cljc:139)
> acc-text-api_1        |     reitit.swagger$create_swagger_handler$create_swagger__25892$transform_endpoint__25903.invoke (swagger.cljc:93)
> acc-text-api_1        |     clojure.core$keep$fn__8559.invoke (core.clj:7337)
> acc-text-api_1        |     clojure.lang.LazySeq.sval (LazySeq.java:42)
> acc-text-api_1        |     clojure.lang.LazySeq.seq (LazySeq.java:51)
> acc-text-api_1        |     clojure.lang.RT.seq (RT.java:535)
> acc-text-api_1        |     clojure.core$seq__5402.invokeStatic (core.clj:137)
> acc-text-api_1        |     clojure.core/seq (core.clj:137)
> acc-text-api_1        |     reitit.swagger$create_swagger_handler$create_swagger__25892$transform_path__25912.invoke (swagger.cljc:97)
> acc-text-api_1        |     clojure.core$map$fn__5866.invoke (core.clj:2753)
> acc-text-api_1        |     clojure.lang.LazySeq.sval (LazySeq.java:42)
> acc-text-api_1        |     clojure.lang.LazySeq.seq (LazySeq.java:51)
> acc-text-api_1        |     clojure.lang.RT.seq (RT.java:535)
> acc-text-api_1        |     clojure.core$seq__5402.invokeStatic (core.clj:137)
> acc-text-api_1        |     clojure.core$apply.invokeStatic (core.clj:660)
> acc-text-api_1        |     clojure.core$apply.invoke (core.clj:660)
> acc-text-api_1        |     reitit.swagger$create_swagger_handler$create_swagger__25892$map_in_order__25919.invoke (swagger.cljc:99)
> acc-text-api_1        |     reitit.swagger$create_swagger_handler$create_swagger__25892.invoke (swagger.cljc:100)
> acc-text-api_1        |     reitit.ring.middleware.exception$wrap$fn__20547$fn__20548.invoke (exception.clj:49)
> acc-text-api_1        |     muuntaja.middleware$wrap_format_response$fn__27254.invoke (middleware.clj:132)
> acc-text-api_1        |     api.server$wrap_response$fn__29685.invoke (server.clj:43)
> acc-text-api_1        |     ring.middleware.params$wrap_params$fn__27201.invoke (params.clj:67)
> acc-text-api_1        |     muuntaja.middleware$wrap_format_negotiate$fn__27247.invoke (middleware.clj:96)
> acc-text-api_1        |     reitit.ring$ring_handler$fn__20513.invoke (ring.cljc:292)
> acc-text-api_1        |     clojure.lang.AFn.applyToHelper (AFn.java:154)
> acc-text-api_1        |     clojure.lang.AFn.applyTo (AFn.java:144)
> acc-text-api_1        |     clojure.lang.AFunction$1.doInvoke (AFunction.java:31)
> acc-text-api_1        |     clojure.lang.RestFn.invoke (RestFn.java:408)
> acc-text-api_1        |     clojure.lang.Var.invoke (Var.java:384)
> acc-text-api_1        |     org.httpkit.server.HttpHandler.run (RingHandler.java:115)
> acc-text-api_1        |     java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
> acc-text-api_1        |     java.util.concurrent.FutureTask.run (FutureTask.java:266)
> acc-text-api_1        |     java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
> acc-text-api_1        |     java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
> acc-text-api_1        |     java.lang.Thread.run (Thread.java:748)` 

Thanks !

**Comment by zmedelis** [comment]
Hi @geopamplona, thanks for reporting this. Indeed there is a problem and will fix it as soon as possible.
