### ISSUE TITLE
Exported document plans should have human readable file names

### ISSUE THREAD

**Issue by zmedelis** [tokenmill/accelerated-text#238]
Current file names are like this `api/resources/document-plans/vsqYQzbYQfOGaQtU.json`.
This makes it hard to manage them manually. We should have DP name in the file name - `My Plan - vsqYQzbYQfOGaQtU.json` or something like that.

**Comment by rokasramas** [comment]
This seems like an easy problem to fix, however, it may have unwanted consequences. For example, when document plans get renamed in UI. After export with such renaming, and if someone is not careful and exports to the same folder as before, there would be two document plans with duplicate IDs - how should we know which one to use after restart?

**Comment by zmedelis** [comment]
We need names to make the manual handling of the files more manageable. We need to get functionality like this:
* list all `doc-plan` or `dgl` files
* find a plan with a specified name (wildcard support)

Some CLI tooling would do the trick for that without introducing tricky file naming.
